// Generated by CoffeeScript 1.6.3
(function() {
  'use strict';
  var App;

  App = angular.module('ReaderProjectApp');

  App.factory('Data', function() {
    var data;
    data = {};
    return {
      'set': function(key, value) {
        return data[key] = value;
      },
      'get': function(key) {
        return data[key];
      },
      'rm': function(key) {
        return delete data[key];
      }
    };
  });

  App.factory('API', [
    '$resource', function($resource) {
      var pageinfo, server;
      server = window.server;
      pageinfo = window.pageinfo;
      return {
        pageinfo: {
          url: $resource("" + pageinfo + "/url/:url", {
            url: '@url'
          }, {
            get: {
              method: 'GET',
              withCredentials: false
            }
          })
        },
        user: $resource("" + server + "/user/:userid", {
          userid: ''
        }),
        check: {
          username: $resource("" + server + "/user/:username/check/", {
            username: '@username'
          }),
          useruri: $resource("" + server + "/checkUseruri/"),
          link: $resource("" + server + "/checkLink/:uri"),
          uri: $resource("" + server + "/checkuri/:uri"),
          email: $resource("" + server + "/email/:email/check", {
            email: '@email'
          })
        },
        sendRegEmail: $resource("" + server + "/email/send/"),
        register: $resource("" + server + "/register/:code", {
          code: '@code'
        }),
        getVerifyCode: "" + server + "/getVerifyCode",
        login: $resource("" + server + "/dologin", {}, {
          save: {
            method: 'POST'
          }
        }),
        summary: $resource("" + server + "/summary/:summaryId"),
        edit: $resource("" + server + "/edit/:summaryId"),
        editUseruri: $resource("" + server + "/edituseruri"),
        collection: $resource("" + server + "/collection/:summaryId", {
          summaryId: '@summaryId'
        }),
        liked: $resource("" + server + "/liked/:summaryId", {
          summaryId: '@summaryId'
        }),
        dislike: $resource("" + server + "/dislike/:summaryId"),
        haveread: $resource("" + server + "/haveread/:summaryId"),
        later: $resource("" + server + "/later/:summaryId"),
        recommend: $resource("" + server + "/recommend/:summaryId/:userid"),
        plusComment: $resource("" + server + "/plus/Comment/:Commentid"),
        comments: {
          one: $resource("" + server + "/comments/:summaryid/", {
            many: $resource("" + server + "/comments/:summaryid/:from/:to")
          })
        },
        singlecomments: $resource("" + server + "/singlecomments/:commentid/:from/:to"),
        getSummary: $resource("" + server + "/:summaryid/:version"),
        article: $resource("" + server + "/article/:summaryid/"),
        recomments: $resource("" + server + "/:recomments/:commentsId"),
        maybelike: $resource("" + server + "/maybelike/summary/:number", {
          number: 10
        }),
        maybelikeSummaryAndTag: $resource("" + server + "/maybelike/summaryAndTag/:number", {
          number: 10
        }),
        op: {
          summary: $resource("" + server + "/op/:operate/summary/:from/:to", {
            operate: 'liked',
            from: 1,
            to: 10
          }),
          summaryAndTag: $resource("" + server + "/op/:operate/summaryandtag/:from/:to", {
            operate: 'liked',
            from: 1,
            to: 10
          }),
          ids: $resource("" + server + "/op/:operate/ids/:from/:to", {
            operate: 'liked',
            from: 1,
            to: 10
          })
        },
        help: {
          test: $resource("" + server + "/help/test")
        },
        timestamp: {
          summary: $resource("" + server + "/timestamp/summary/:summaryid"),
          tag: $resource("" + server + "/timestamp/tag/:summaryid"),
          commented: $resource("" + server + "/timestamp/commented/:summaryid")
        },
        j: $resource("" + server + "/j/:uri"),
        readetimes: $resource("" + server + "/readetimes/:summaryid"),
        url: $resource("" + server + "/uri/:summaryid"),
        id: $resource("" + server + "/id/:url"),
        atMe: $resource("" + server + "/atme/sum/:read"),
        messageSum: $resource("" + server + "/message/sum/:read"),
        message: $resource("" + server + "/:touserid"),
        fans: $resource("" + server + "/fans/:from/:to"),
        sum: {
          fans: $resource("" + server + "/sum/fans/:userid", {
            userid: ''
          }),
          follow: $resource("" + server + "/sum/follow"),
          tag: $resource("" + server + "/sum/tag")
        },
        my: {
          tag: $resource("" + server + "/my/tag/:from/:to"),
          sum: {
            tag: $resource("" + server + "/my/sum/tag")
          }
        },
        follow: {
          get: $resource("" + server + "/follow/:from/:to"),
          one: $resource("" + server + "/follow/:userid")
        },
        tag: {
          one: $resource("" + server + "/tag/:tagid"),
          many: $resource("" + server + "/tag/:from/:to"),
          summary: $resource("" + server + "/:summaryid/:version")
        },
        score: {
          summary: {
            one: $resource("" + server + "/score/summary/:summaryid"),
            avg: $resource("" + server + "/score/avg/summary/:summaryid"),
            sum: $resource("" + server + "/score/sum/summary/:summaryid"),
            distribution: $resource("" + server + "/score/distribution/summary/:summaryid")
          }
        },
        danger: {
          summaryAndTag: $resource("" + server + "/summaryandtag/:summaryid/:version"),
          summaryAndTagAndComments: $resource("" + server + "/summaryandtagandComments/:summaryid/:version"),
          summaryAndTagAndCommentAndActicle: $resource("/summaryandtagandCommentandacticle/:summaryid/:version")
        }
      };
    }
  ]);

}).call(this);
