// Generated by CoffeeScript 1.6.3
(function() {
  'use strict';
  var App;

  App = angular.module('ReaderProjectApp');

  App.filter('isExist', function() {
    return function(input) {
      return input != null;
    };
  });

  App.filter('shortUrl', function() {
    return function(input) {
      return "" + window.server + "/j/" + input;
    };
  });

  App.filter('md5', function() {
    return function(input) {
      return md5(input);
    };
  });

  App.filter('gravatar', function() {
    return function(input, size) {
      return "http://www.gravatar.com/avatar/" + (md5(input)) + "?s=" + (size || 32);
    };
  });

  App.filter('avatar', function() {
    return function(input, size) {
      return "" + window.server + "/avatar/" + input + (size ? '/size/' + size : '');
    };
  });

  App.filter('tag2String', function() {
    return function(input) {
      if (_.isArray(input)) {
        return input.join(', ');
      } else {
        return input;
      }
    };
  });

  App.filter('tag2Array', function() {
    return function(input) {
      if (_.isString(input)) {
        return input.split(',');
      } else {
        return input;
      }
    };
  });

}).call(this);
