// Generated by CoffeeScript 1.6.3
(function() {
  'use strict';
  var App;

  App = angular.module('ReaderProjectApp');

  App.controller('LoginCtrl', function($scope, $timeout, $location, $rootScope, API, Restangular) {
    var hideAlert, showAlert;
    if ($rootScope.user.logged) {
      $location.path('/');
    }
    showAlert = function(status, text) {
      $scope.alertType = status;
      return $scope.alert = text;
    };
    hideAlert = function() {
      $scope.alertType = false;
      return $scope.alert = false;
    };
    $scope.getVerifyCode = API.getVerifyCode;
    $scope.logged = false;
    return $scope.login = function() {
      return Restangular.all('dologin').post({
        email: $scope.email,
        password: $scope.password,
        auto: $scope.remember
      }).then(function(result) {
        var _ref;
        if (result.message) {
          localStorage['token'] = result.message;
        }
        Restangular.setDefaultHeaders({
          'Token': (_ref = localStorage['token']) != null ? _ref : ''
        });
        $rootScope.user.logged = true;
        Restangular.all('user').getList().then(function(result) {
          return $rootScope.user.name = result.userName;
        });
        Restangular.one('user', 'tag').getList().then(function(result) {
          var followedTag, tag;
          followedTag = (function() {
            var _i, _len, _results;
            _results = [];
            for (_i = 0, _len = result.length; _i < _len; _i++) {
              tag = result[_i];
              _results.push(tag.tagName);
            }
            return _results;
          })();
          $rootScope.user.followedTag = followedTag;
          return console.log(followedTag);
        });
        $scope.logged = true;
        showAlert('success', '登录成功! 接下来将为您跳转到首页.');
        return $timeout(function() {
          return $location.path('/');
        }, 3000);
      }, function(response) {
        if (response.status === 0) {
          return showAlert('danger', '服务器正在维护');
        } else {
          console.log(response);
          return showAlert('danger', '发生错误, 请检查填写的信息后重试');
        }
      });
    };
  });

}).call(this);
