// Generated by CoffeeScript 1.6.3
(function() {
  'use strict';
  var App;

  App = angular.module('ReaderProjectApp');

  App.controller('NavCtrl', function($scope, $rootScope, $timeout, Restangular, $location) {
    var autoLogin;
    $scope.user = $rootScope.user = {
      logged: false
    };
    $scope.path = $location.path();
    $scope.$on('$locationChangeSuccess', function() {
      return $scope.path = $location.path();
    });
    $scope.logout = function() {
      return Restangular.one('logout').get().then(function(value) {
        localStorage['token'] = null;
        return $rootScope.user = {
          logged: false
        };
      });
    };
    $rootScope.$watch('user', function(newValue, oldValue) {
      if (newValue !== oldValue) {
        return $scope.user = $rootScope.user;
      }
    }, true);
    autoLogin = function() {
      return Restangular.all('user').getList().then(function(result) {
        Restangular.one('user', 'tag').getList().then(function(result) {
          var followedTag, tag;
          followedTag = (function() {
            var _i, _len, _results;
            _results = [];
            for (_i = 0, _len = result.length; _i < _len; _i++) {
              tag = result[_i];
              _results.push(tag.tagName);
            }
            return _results;
          })();
          $rootScope.user.followedTag = followedTag;
          return console.log(followedTag);
        });
        $rootScope.user.name = result.userName;
        $rootScope.user.logged = true;
        return $timeout(autoLogin, 30 * 1000);
      }, function(response) {
        var token;
        token = localStorage['token'];
        if (token) {
          return Restangular.one('dologin').post().then(function(value) {
            $rootScope.user.logged = true;
            return autoLogin();
          });
        }
      });
    };
    return autoLogin();
  });

}).call(this);
