// Generated by CoffeeScript 1.6.3
(function() {
  'use strict';
  var App;

  App = angular.module('ReaderProjectApp');

  App.controller('SettingCtrl', function($scope, $rootScope, $location, Restangular) {
    var _ref;
    if (!$rootScope.user.logged) {
      $location.path('/');
    }
    $scope.backgroundImageUrl = (_ref = localStorage['backgroundImageUrl']) != null ? _ref : '';
    return $scope.setting = function() {
      console.log($rootScope.setBackground);
      return $rootScope.setBackground($scope.backgroundImageUrl);
    };
  });

}).call(this);
