// Generated by CoffeeScript 1.6.3
(function() {
  'use strict';
  var App;

  App = angular.module('ReaderProjectApp');

  App.controller('SignCtrl', function($scope, $rootScope, $timeout, $location, Restangular) {
    var hideAlert, showAlert;
    if ($rootScope.user.logged) {
      $location.path('/');
    }
    $scope.checkUserName = function() {
      return Restangular.one('user', $scope.username).all('check').get().then(function(value) {
        if (value.message === false) {
          return console.log('已被占用');
        }
      });
    };
    showAlert = function(status, text) {
      $scope.alertType = status;
      return $scope.alert = text;
    };
    hideAlert = function() {
      $scope.alertType = false;
      return $scope.alert = false;
    };
    $scope.panelEmail = true;
    $scope.panelSign = false;
    $scope.panelSuccess = false;
    if ($location.search().panelSign) {
      $scope.panelEmail = false;
      $scope.panelSign = true;
      $scope.panelSuccess = false;
    }
    return $scope.sendRegEmail = function() {
      hideAlert();
      return Restangular.one('email', $scope.email).all('check').get().then(function(value) {
        return Restangular.all('email').all('send').post().then(function(value) {
          $scope.panelEmail = false;
          return $scope.panelSign = true;
        }, function(response) {
          return showAlert('danger', '发送失败, 请稍后重试.');
        });
      }, function(response) {
        return showAlert('danger', '该邮箱已经被用于注册.');
      });
    };
    /*
    $scope.register = ->
        hideAlert()
        if $scope.password is $scope.confirmPassword
            Restangular.one('register', $scope.regCode).post(
                userName:$scope.username
                passowrd:$scope.password
            ).then (value)->
                $scope.panelSign = false
                showAlert 'success', '注册成功! 接下来将为您跳转到登录页面.'
                $timeout ->
                    $location.path '/login'
                ,3000
            ,(response)->
                showAlert 'danger', '发生错误'
        else
            showAlert 'warning', '密码填写不一致'
    */

  });

}).call(this);
